#!/bin/bash -e

mkdir -p "$HOME"/.local/share

mkdir build
cd build
export TZ="America/Los_Angeles"

if [[ "$BUILDTYPE" == "cmake-make" ]]; then
    cmake ../gnucash
    make
    make check || ../afterfailure
elif [[ "$BUILDTYPE" == "cmake-ninja" ]]; then
    cmake ../gnucash -DWITH_PYTHON=ON -DCMAKE_BUILD_TYPE=debug -G Ninja \
    -DPYTHON_EXECUTABLE=/usr/bin/python2.7 \
    -DGTEST_ROOT=/usr/include/gtest -DGMOCK_ROOT=/usr/include/gmock
    ninja -v
    ninja check || ../afterfailure;
else
    echo "Unknown buildtype: \"$BUILDTYPE\". Not building."
fi
