#!/bin/bash -le

mkdir ourpython_bin
ln -s /usr/bin/python ourpython_bin/python
export PATH=/ourpython_bin:"$PATH"
echo path is "$PATH"
echo python version is "$(python --version)"

export GTEST_ROOT=/usr/include/gtest/src GMOCK_ROOT=/usr/include/gmock/src

../commonbuild
