#!/bin/bash -e

# -e above so that if any command has an exit code != 0, this script will
#  exit immediately.

export GTEST_ROOT=/usr/include/gtest/src GMOCK_ROOT=/usr/include/gmock/src

../commonbuild
