# Test
sudo: required
language: c++
compiler: gcc
env:
    - BUILDENV=tumbleweed BUILDTYPE=cmake-ninja
services:
    - docker
install:
    - docker --version
    - echo BUILDENV="$BUILDENV"
    - docker build -f util/ci/${BUILDENV}-docker -t ${BUILDENV}-gnucashbuild util/ci
script:
    - echo BUILDTYPE="$BUILDTYPE"
    - docker run -v "$(pwd)":/gnucash:rw --env="BUILDTYPE=$BUILDTYPE" --rm ${BUILDENV}-gnucashbuild
